[package]
name = "clash-rs"
# repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
# homepage = { workspace = true }
# authors = { workspace = true }

[features]
default = ["standard"]
standard = []

plus = ["standard", "onion"]
onion = []

perf = ["plus", "jemallocator"]
# todo
jemallocator = [""]
