[package]
name = "chimera-dns"
# repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
# homepage = { workspace = true }
# authors = { workspace = true }

[dependencies]
# hickory-proto = "0.24"
thiserror = "2"
futures = "0.3"
