[package]
name = "chimera-dns"
# repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
# homepage = { workspace = true }
# authors = { workspace = true }

[dependencies]
thiserror = "2"
futures = "0.3"

async-trait = "0.1"

hickory-server = { version = "0.25", default-features = false }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
