[package]
name = "clash-lib"
# repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
# homepage = { workspace = true }
# authors = { workspace = true }


[dependencies]
# Error handing & logging
thiserror = "2"
anyhow = "1"

# Async
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

tracing = "0.1"
tracing-log = "0.2"
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "local-time",
] }
time = { version = "=0.3", features = ["macros", "local-offset"] }

rustls = { version = "0.23", default-features = false }

uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }

# dns
chimera-dns = { path = "../clash-dns", default-features = false }

[features]
default = ["zero_copy", "aws-lc-rs"]

zero_copy = []

aws-lc-rs = ["rustls/aws-lc-rs"]
