[package]
name = "clash-lib"
# repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
# homepage = { workspace = true }
# authors = { workspace = true }


[dependencies]
# Error handing & logging
thiserror = "2"
anyhow = "1"

# Async
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
http = "1"
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
bytes = "1"
tokio-rustls = "0.26"
webpki-roots = "0.26"
maxminddb = "0.27"
hickory-proto = "0.24"

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

tracing = "0.1"
tracing-log = "0.2"
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "local-time",
] }
time = { version = "=0.3", features = ["macros", "local-offset"] }

rustls = { version = "0.23", default-features = false }

uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }

# dns
chimera-dns = { path = "../clash-dns", default-features = false }

# Macro Magic
educe = "0.6"

socket2 = { version = "0.6", features = ["all"] }

# experimental
downcast-rs = "2.0"

rand = "0.9"

[features]
default = ["zero_copy", "aws-lc-rs"]

zero_copy = []

aws-lc-rs = ["rustls/aws-lc-rs"]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Networking_WinSock",
    "Win32_Foundation",
    "Win32_NetworkManagement_Rras",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis"
] }
