[package]
name = "clash-lib"
# repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
# homepage = { workspace = true }
# authors = { workspace = true }


[dependencies]
# Error handing & logging
thiserror = "2"

# Async
tokio = { version = "1", features = ["full"] }

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
